/**
 * Parses the output message generated by La Cuota into a structured
 * list of person → amount pairs, WITHOUT calling any AI API.
 *
 * La Cuota message format:
 * 👤 *Pedro*: $5.500
 *    • Cerveza: $3.500
 *    • Propina: $2.000
 *
 * 👤 *Ana*: $7.200
 *    • Sushi: $7.200
 */

export type ParsedPerson = { name: string; amount: number };

/** Strips currency formatting: "$5.500", "5,500", "CLP 5500" → 5500 */
function parseAmount(raw: string): number {
  // Remove currency symbols and codes
  let s = raw.replace(/[A-Z]{3}\s*/g, '').replace(/[$R\s]/g, '');
  
  const commaIdx = s.lastIndexOf(',');
  const dotIdx = s.lastIndexOf('.');
  
  if (commaIdx > dotIdx) {
    // comma is decimal separator: 1.234,56
    s = s.replace(/\./g, '').replace(',', '.');
  } else if (dotIdx > -1) {
    // Only dots are present, or dot is after comma (unlikely but handled)
    // Heuristic: if the last dot is followed by exactly 3 digits, it's likely a thousands separator (CLP)
    const parts = s.split('.');
    const lastPart = parts[parts.length - 1];
    
    if (lastPart.length === 3 && parts.length > 1) {
      // It's a thousands separator: 46.900 -> 46900
      s = s.replace(/\./g, '');
    } else {
      // It's a decimal separator or something else: 46.9 -> 46.9
      s = s.replace(/,/g, '');
    }
  } else {
    // No dots or commas
    s = s.replace(/,/g, '');
  }
  
  return parseFloat(s) || 0;
}

function normalize(s: string) {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

export function parseLaCuotaMessage(text: string): ParsedPerson[] {
  const people: ParsedPerson[] = [];
  const lines = text.split('\n');

  // ── Mode 1: Standard La Cuota format (👤 *Pedro*: $5.500) ──────────────────
  for (const line of lines) {
    const trimmed = line.trim();
    const personLineMatch =
      trimmed.match(/^👤\s+\*?([^*:,]+)\*?\s*:\s*(.+)$/) ||
      trimmed.match(/^👋\s+[Hh]ola\s+\*?([^*,]+)\*?,\s+tu parte.*es de\s+\*?([^*\s]+)/);

    if (personLineMatch) {
      const name = personLineMatch[1].trim();
      const amountStr = personLineMatch[2].trim();
      const amount = parseAmount(amountStr);
      if (name && amount > 0) {
        people.push({ name, amount });
      }
    }
  }

  if (people.length > 0) return people;

  // ── Mode 2: Football / numbered player list ─────────────────────────────────
  // Detect lines like: "1. Neto", "2. Rodo (a)", "3. Iván"
  // Also detect a total: "$6.000", "Total: 6000", "canchas 6 $6.000", etc.
  const playerLines: string[] = [];
  let detectedTotal = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Numbered player: "1. Neto", "2. Rodo (a)", "10. García"
    const playerMatch = trimmed.match(/^\d+[\.\)]\s*(.+)$/);
    if (playerMatch) {
      // Clean up annotations like "(a)", "(c)", "(s)", etc.
      const rawName = playerMatch[1].replace(/\s*\([a-zA-Z]\)\s*$/, '').trim();
      if (rawName.length > 0) {
        playerLines.push(rawName);
      }
      continue;
    }

    // Detect a standalone total amount anywhere in the text
    // e.g. "$6.000", "Total: $6.000", "canchas 6 campanil $6.000"
    const totalMatch =
      trimmed.match(/total\s*:?\s*\$?([\d.,]+)/i) ||
      trimmed.match(/\$\s*([\d.,]+)\s*$/i) ||
      trimmed.match(/^([\d.,]+)\s*$/) ||
      trimmed.match(/(?:^|\s)\$\s*([\d.,]+)/i);

    if (totalMatch) {
      const parsed = parseAmount(totalMatch[1] ?? totalMatch[0]);
      if (parsed > 0) detectedTotal = parsed;
    }
  }

  if (playerLines.length > 0 && detectedTotal > 0) {
    const share = Math.round(detectedTotal / playerLines.length);
    playerLines.forEach(name => people.push({ name, amount: share }));
  } else if (playerLines.length > 0 && detectedTotal === 0) {
    // Return names with amount=0 so the UI shows them (user enters total manually)
    playerLines.forEach(name => people.push({ name, amount: 0 }));
  }

  return people;
}


/**
 * Finds a matching member by name (exact or prefix match, accent-insensitive).
 */
export function findMemberMatch(
  parsedName: string,
  members: { id: string; name: string }[]
): string | null {
  const n = normalize(parsedName);
  // Only exact match (normalized)
  const exact = members.find((m) => normalize(m.name) === n);
  return exact?.id ?? null;
}
