/**
 * Parses the output message generated by La Cuota into a structured
 * list of person → amount pairs, WITHOUT calling any AI API.
 *
 * La Cuota message format:
 * 👤 *Pedro*: $5.500
 *    • Cerveza: $3.500
 *    • Propina: $2.000
 *
 * 👤 *Ana*: $7.200
 *    • Sushi: $7.200
 */

export type ParsedPerson = { name: string; amount: number };

/** Strips currency formatting: "$5.500", "5,500", "CLP 5500" → 5500 */
function parseAmount(raw: string): number {
  // Remove currency symbols and codes
  let s = raw.replace(/[A-Z]{3}\s*/g, '').replace(/[$R\s]/g, '');
  // Detect if comma is decimal separator (e.g. "7,20") or thousands (e.g. "7,500")
  const commaIdx = s.lastIndexOf(',');
  const dotIdx = s.lastIndexOf('.');
  if (commaIdx > dotIdx) {
    // comma is decimal separator: 1.234,56
    s = s.replace(/\./g, '').replace(',', '.');
  } else {
    // dot is decimal separator or thousands: 1,234.56 or 5.500
    s = s.replace(/,/g, '');
  }
  return parseFloat(s) || 0;
}

function normalize(s: string) {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

export function parseLaCuotaMessage(text: string): ParsedPerson[] {
  const people: ParsedPerson[] = [];

  const lines = text.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Match person lines: "👤 *Pedro*: $5.500" or "👤 Pedro: $5.500"
    // Also matches "Hola *Pedro*, tu parte en *La Cuota* es de *$5.500*"
    const personLineMatch =
      trimmed.match(/^👤\s+\*?([^*:,]+)\*?\s*:\s*(.+)$/) ||
      trimmed.match(/^👋\s+[Hh]ola\s+\*?([^*,]+)\*?,\s+tu parte.*es de\s+\*?([^*\s]+)/);

    if (personLineMatch) {
      const name = personLineMatch[1].trim();
      const amountStr = personLineMatch[2].trim();
      const amount = parseAmount(amountStr);
      if (name && amount > 0) {
        people.push({ name, amount });
      }
    }
  }

  return people;
}

/**
 * Finds a matching member by name (exact or prefix match, accent-insensitive).
 */
export function findMemberMatch(
  parsedName: string,
  members: { id: string; name: string }[]
): string | null {
  const n = normalize(parsedName);
  // Exact match
  const exact = members.find((m) => normalize(m.name) === n);
  if (exact) return exact.id;
  // Prefix match (handles "Anto" / "Antonella", "Sebas" / "Sebastian")
  const partial = members.find((m) => {
    const mn = normalize(m.name);
    return mn.startsWith(n) || n.startsWith(mn);
  });
  return partial?.id ?? null;
}
