/**
 * Parses the output message generated by La Cuota into a structured
 * list of person → amount pairs, WITHOUT calling any AI API.
 *
 * La Cuota message format:
 * 👤 *Pedro*: $5.500
 *    • Cerveza: $3.500
 *    • Propina: $2.000
 *
 * 👤 *Ana*: $7.200
 *    • Sushi: $7.200
 */

export type ParsedPerson = { name: string; amount: number };

/** Strips currency formatting: "$5.500", "5,500", "CLP 5500" → 5500 */
function parseAmount(raw: string): number {
  // Remove currency symbols and codes
  let s = raw.replace(/[A-Z]{3}\s*/g, '').replace(/[$R\s]/g, '');
  
  const commaIdx = s.lastIndexOf(',');
  const dotIdx = s.lastIndexOf('.');
  
  if (commaIdx > dotIdx) {
    // comma is decimal separator: 1.234,56
    s = s.replace(/\./g, '').replace(',', '.');
  } else if (dotIdx > -1) {
    // Only dots are present, or dot is after comma (unlikely but handled)
    // Heuristic: if the last dot is followed by exactly 3 digits, it's likely a thousands separator (CLP)
    const parts = s.split('.');
    const lastPart = parts[parts.length - 1];
    
    if (lastPart.length === 3 && parts.length > 1) {
      // It's a thousands separator: 46.900 -> 46900
      s = s.replace(/\./g, '');
    } else {
      // It's a decimal separator or something else: 46.9 -> 46.9
      s = s.replace(/,/g, '');
    }
  } else {
    // No dots or commas
    s = s.replace(/,/g, '');
  }
  
  return parseFloat(s) || 0;
}

function normalize(s: string) {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

export function parseLaCuotaMessage(text: string): ParsedPerson[] {
  const people: ParsedPerson[] = [];

  const lines = text.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Match person lines: "👤 *Pedro*: $5.500" or "👤 Pedro: $5.500"
    // Also matches "Hola *Pedro*, tu parte en *La Cuota* es de *$5.500*"
    const personLineMatch =
      trimmed.match(/^👤\s+\*?([^*:,]+)\*?\s*:\s*(.+)$/) ||
      trimmed.match(/^👋\s+[Hh]ola\s+\*?([^*,]+)\*?,\s+tu parte.*es de\s+\*?([^*\s]+)/);

    if (personLineMatch) {
      const name = personLineMatch[1].trim();
      const amountStr = personLineMatch[2].trim();
      const amount = parseAmount(amountStr);
      if (name && amount > 0) {
        people.push({ name, amount });
      }
    }
  }

  return people;
}

/**
 * Finds a matching member by name (exact or prefix match, accent-insensitive).
 */
export function findMemberMatch(
  parsedName: string,
  members: { id: string; name: string }[]
): string | null {
  const n = normalize(parsedName);
  // Only exact match (normalized)
  const exact = members.find((m) => normalize(m.name) === n);
  return exact?.id ?? null;
}
